version: 0.2
 
phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 675628601405.dkr.ecr.ap-south-1.amazonaws.com
      - REPOSITORY_URI=675628601405.dkr.ecr.ap-south-1.amazonaws.com/brain-tasks-app
      - IMAGE_TAG=$CODEBUILD_BUILD_NUMBER
 
  build:
    commands:
      - echo Build started on `date`
      - echo Building Docker image...
      - docker build -t $REPOSITORY_URI:$IMAGE_TAG .
      - docker tag $REPOSITORY_URI:$IMAGE_TAG $REPOSITORY_URI:latest
 
  post_build:
    commands:
      - echo Pushing Docker image to ECR...
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - docker push $REPOSITORY_URI:latest
      - echo Build completed on `date`